# Tensors

Tutorial link: [PyTorch Docs](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

----

In [1]:
import torch
import numpy as np

## 1. Initializing a Tensor

In [2]:
data = [[1,2], [3, 4]]
x_data = torch.tensor(data) # tensor from regular Python List

np_array = np.array(data)
x_np = torch.from_numpy(np_array) # tensor ffrom numpy ndarray


In [5]:
x_data.dtype, x_np.dtype, np_array.dtype

(torch.int64, torch.int64, dtype('int64'))

In [7]:
x_ones = torch.ones_like(x_data)
x_ones, x_ones.dtype

(tensor([[1, 1],
         [1, 1]]),
 torch.int64)

In [8]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
x_rand, x_rand.dtype

(tensor([[0.1342, 0.7358],
         [0.1265, 0.7839]]),
 torch.float32)

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

rand_tensor, ones_tensor, zeros_tensor

(tensor([[0.4138, 0.8138, 0.8231],
         [0.3927, 0.6102, 0.2390]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

## 2. Attributes of a Tensor

In [11]:
tensor = torch.rand(shape)
tensor

tensor([[0.8564, 0.6403, 0.2223],
        [0.8531, 0.4990, 0.4861]])

In [12]:
tensor.shape, tensor.dtype, tensor.device

(torch.Size([2, 3]), torch.float32, device(type='cpu'))

## 3. Operations on Tensors

In [13]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
    print("Tensor moved to non-CPU architecture!")
else:
    print("No accelator available, tensor will remain on the CPU")

No accelator available, tensor will remain on the CPU


In [15]:
tensor = torch.rand(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.4627, 0.9993, 0.2908, 0.5975])
First column: tensor([0.4627, 0.3039, 0.0042, 0.3406])
Last column: tensor([0.5975, 0.1933, 0.9043, 0.4034])
tensor([[0.4627, 0.0000, 0.2908, 0.5975],
        [0.3039, 0.0000, 0.8740, 0.1933],
        [0.0042, 0.0000, 0.4901, 0.9043],
        [0.3406, 0.0000, 0.8763, 0.4034]])


In [16]:
tensor[:,-1]

tensor([0.5975, 0.1933, 0.9043, 0.4034])

In [18]:
torch.cat([tensor, tensor], dim=1)

tensor([[0.4627, 0.0000, 0.2908, 0.5975, 0.4627, 0.0000, 0.2908, 0.5975],
        [0.3039, 0.0000, 0.8740, 0.1933, 0.3039, 0.0000, 0.8740, 0.1933],
        [0.0042, 0.0000, 0.4901, 0.9043, 0.0042, 0.0000, 0.4901, 0.9043],
        [0.3406, 0.0000, 0.8763, 0.4034, 0.3406, 0.0000, 0.8763, 0.4034]])

In [19]:
agg = tensor.sum()
agg_item = agg.item()
agg, agg_item

(tensor(5.7411), 5.741137504577637)

## 4. Bridge with NumPy

In [20]:
t = torch.ones(5)
n = t.numpy()
t, n

(tensor([1., 1., 1., 1., 1.]), array([1., 1., 1., 1., 1.], dtype=float32))

In [21]:
t.add_(1) # the numpy array is also changed
t, n

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [22]:
np.add(n, 10, out=n)
t, n

(tensor([12., 12., 12., 12., 12.]),
 array([12., 12., 12., 12., 12.], dtype=float32))