# Build the Neural Network

---

https://docs.pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html

In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import numpy as np
import matplotlib.pyplot as plt

In [2]:
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else 'cpu'
print("Current device", device)

Current device cpu


## Define the Class

In [5]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [6]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [7]:
X = torch.rand(1, 28, 28, device=device)
logits = model(X)
logits.shape, logits

(torch.Size([1, 10]),
 tensor([[-0.0313, -0.0251,  0.0816,  0.0862, -0.0103,  0.0279,  0.0789, -0.0810,
          -0.0595, -0.0143]], grad_fn=<AddmmBackward0>))

In [10]:
logits[0]

tensor([-0.0313, -0.0251,  0.0816,  0.0862, -0.0103,  0.0279,  0.0789, -0.0810,
        -0.0595, -0.0143], grad_fn=<SelectBackward0>)

In [15]:
nn.Softmax(dim=1)(logits)

tensor([[0.0962, 0.0968, 0.1078, 0.1082, 0.0983, 0.1021, 0.1075, 0.0916, 0.0936,
         0.0979]], grad_fn=<SoftmaxBackward0>)

In [18]:
predicted_probability = nn.Softmax(dim=1)(logits)
predicted_y = predicted_probability.argmax(dim=1)
predicted_y

tensor([3])